# Generated by Django 2.1.15 on 2021-02-14 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Price', models.FloatField()),
                ('Quantity', models.IntegerField()),
                ('ShortDesc', models.TextField()),
                ('LongDesc', models.TextField()),
                ('Picture', models.ImageField(upload_to='images')),
                ('Stock', models.BooleanField(default=True, max_length=50)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superuser.Categories')),
            ],
        ),
        migrations.CreateModel(
            name='TT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=800)),
            ],
        ),
    ]
