# Generated by Django 2.1.15 on 2021-02-14 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food_delivery_admin', '0005_tt'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionid', models.CharField(max_length=60, null=True)),
                ('itemname', models.CharField(blank=True, max_length=60, null=True)),
                ('itemprice', models.CharField(blank=True, max_length=60, null=True)),
                ('actualitem', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='food_delivery_admin.Item')),
            ],
        ),
        migrations.CreateModel(
            name='cartitemdetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Price', models.FloatField(default=0.0)),
                ('Quantity', models.IntegerField(blank=True, null=True)),
                ('ShortDesc', models.TextField(blank=True, null=True)),
                ('LongDesc', models.TextField(blank=True, null=True)),
                ('Picture', models.ImageField(default='/media/c/1.jpg', upload_to='images')),
                ('Stock', models.BooleanField(default=True, max_length=50)),
                ('Category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='food_delivery_admin.Categories')),
            ],
        ),
        migrations.CreateModel(
            name='mailings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callnumber', models.CharField(blank=True, max_length=60, null=True)),
                ('counter', models.CharField(blank=True, max_length=60, null=True)),
                ('is_delivered', models.BooleanField(default=False)),
                ('subtotal', models.FloatField(default=0.0)),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cartitemdetail',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='public.order'),
        ),
    ]
