# Generated by Django 2.2.10 on 2020-05-20 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_delivery_admin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
