# Generated by Django 2.2.10 on 2020-05-20 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_delivery_admin', '0002_delete_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Price', models.FloatField()),
                ('Quantity', models.IntegerField()),
                ('ShortDesc', models.TextField()),
                ('LongDesc', models.TextField()),
                ('Picture', models.ImageField(upload_to='images')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_delivery_admin.Categories')),
            ],
        ),
    ]
