# Generated by Django 2.2.10 on 2020-05-24 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_delivery_admin', '0003_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='Stock',
            field=models.BooleanField(default=True, max_length=50),
        ),
    ]
