# Generated by Django 2.2.10 on 2020-05-29 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_delivery_admin', '0004_item_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='TT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=800)),
            ],
        ),
    ]
